apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "blaksoc.fullname" . }}-worker
  labels: {{- include "blaksoc.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels: { app.kubernetes.io/instance: {{ .Release.Name }}, app.kubernetes.io/component: worker }
  template:
    metadata:
      labels: {{- include "blaksoc.labels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: 60
      containers:
        - name: worker
          image: {{ include "blaksoc.image" (dict "root" . "target" "worker") }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- include "blaksoc.env" . | nindent 12 }}
          envFrom:
            - secretRef:
                name: {{ .Values.existingSecret }}
          resources: {{- toYaml .Values.worker.resources | nindent 12 }}
          securityContext: {{- toYaml .Values.securityContext | nindent 12 }}
          volumeMounts: [{ name: tmp, mountPath: /tmp }]
      volumes: [{ name: tmp, emptyDir: {} }]
